#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot TPE learning_rate vs accuracy.")
    parser.add_argument(
        "--leaderboard",
        type=str,
        default="outputs/hparam_search/leaderboard.csv",
        help="Path to leaderboard.csv generated by TPE search.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="outputs/hparam_search/lr_vs_accuracy.png",
        help="Output image path.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="TPE: learning_rate vs boxed accuracy",
        help="Plot title.",
    )
    return parser.parse_args()


def _read_points(leaderboard_path: Path) -> tuple[list[float], list[float], str]:
    with leaderboard_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        acc_cols = [h for h in headers if h.startswith("boxed_acc_step")]
        if not acc_cols:
            raise ValueError("No boxed accuracy column found in leaderboard.")
        acc_col = acc_cols[0]

        x_lr: list[float] = []
        y_acc: list[float] = []
        for row in reader:
            if row.get("status", "").lower() != "complete":
                continue
            lr_raw = row.get("learning_rate")
            acc_raw = row.get(acc_col)
            if lr_raw is None or acc_raw is None:
                continue
            x_lr.append(float(lr_raw))
            y_acc.append(float(acc_raw))

    if not x_lr:
        raise ValueError("No complete trials found in leaderboard.")
    return x_lr, y_acc, acc_col


def main() -> None:
    args = parse_args()
    leaderboard_path = Path(args.leaderboard)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    x_lr, y_acc, acc_col = _read_points(leaderboard_path)

    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError("matplotlib is required. Please run: pip install matplotlib") from exc

    points = sorted(zip(x_lr, y_acc), key=lambda p: p[0])
    x_sorted = [p[0] for p in points]
    y_sorted = [p[1] for p in points]

    best_idx = max(range(len(y_acc)), key=lambda i: y_acc[i])
    best_lr = x_lr[best_idx]
    best_acc = y_acc[best_idx]

    plt.figure(figsize=(10, 6))
    plt.scatter(x_lr, y_acc, alpha=0.8, label="Trials")
    plt.plot(x_sorted, y_sorted, alpha=0.5, linestyle="--", linewidth=1, label="Trend (sorted by lr)")
    plt.scatter([best_lr], [best_acc], marker="*", s=220, label="Best trial")
    plt.xscale("log")
    plt.xlabel("learning_rate (log scale)")
    plt.ylabel(acc_col)
    plt.title(args.title)
    plt.grid(True, linestyle="--", alpha=0.35)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    plt.close()

    print(f"Saved plot: {output_path}")
    print(f"Best point: lr={best_lr:.6g}, {acc_col}={best_acc:.4f}")


if __name__ == "__main__":
    main()

